cases = [
    'konwentor.convent.tests.test_forms:ConventAddFormTest',
    'konwentor.convent.tests.test_forms:ConventDeleteFormTest',
    'konwentor.convent.tests.test_database:ConventDatabaseTest',
    'konwentor.statistics.tests.test_controller:StatisticsControllerTest',
    'konwentor.statistics.tests.test_controller:StatisticsSqlsTest',
    'konwentor.gameborrow.tests.test_models:GameBorrowUnitTestCase',
    'konwentor.auth.tests.test_models:UserTestCase',
    'konwentor.auth.tests.test_models:NotLoggedUserTestCase',
    'konwentor.forms.tests.test_forms:PostFormTest',
    'konwentor.gamecopy.tests.test_forms:GameCopyAddFormTest',
    'konwentor.gamecopy.tests.test_forms:GameCopyAddFormSqlTestCase',
    'konwentor.gamecopy.tests.test_controller:GameCopyControllerBaseTests',
    'konwentor.gamecopy.tests.test_controller:GameCopyControllerBaseSqlTests',
    'konwentor.gamecopy.tests.test_controller:GameCopyListControllerTestCase',
]
