version: '3.1'

services:
  backend:
    build: .
    command: uwsgi --ini-paste data/frontend.ini
    env_file: .env
    tty: true
    stdin_open: true
    volumes:
      - ./code:/code
    ports:
      - "${BACKEND_POR:-5001}:8000"

  postgres:
    image: postgres:9.4
    env_file: .env
    labels:
      - "traefik.enable=false"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=iamsuperkonwent
      - POSTGRES_USER=konwentor
      - POSTGRES_DB=konwentor_live

volumes:
  postgres-data:
