version: '3.3'

services:
  backend:
    build: .
    image: registry.socek.org/konwentor:$VERSION
    env_file: env
    volumes:
      - ./code:/code
    ports:
      - 5001:8000"

  postgres:
    image: postgres:9.5
    env_file: env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dumps:/dumps


volumes:
  postgres-data:
