convent:
    controllers:
        -
            controller: ConventListController
            route: convent:list
            url: /
        -
            controller: ConventAdd
            route: convent:add
            url: /convent/add
        -
            controller: ConventDelete
            route: convent:delete
            url: /convent/delete/{obj_id:\d+}
        -
            controller: ChooseConventController
            route: convent:choose
            url: /convent/choose/{obj_id:\d+}
        -
            controller: StartConventController
            route: convent:start
            url: /convent/start/{obj_id:\d+}
        -
            controller: EndConventController
            route: convent:end
            url: /convent/end/{obj_id:\d+}
        -
            controller: ConventEditController
            route: convent:edit
            url: /convent/edit/{obj_id:\d+}

game:
    controllers:
        -
            controller: GameListController
            route: game:list
            url: /games

        -
            controller: GameAddController
            route: game:add
            url: /game/add
        -
            controller: GameDelete
            route: game:delete
            url: /game/delete/{obj_id:\d+}
        -
            controller: GameEditController
            route: game:edit
            url: /game/edit/{obj_id:\d+}

gamecopy:
    controllers:
        -
            controller: GameCopyAddController
            route: gamecopy:add
            url: /{convent_id:\d+}/gamecopy/{room_id:\d+}/add
        -
            controller: GameCopyListController
            route: gamecopy:list
            url: /{convent_id:\d+}/gamecopy/{room_id:\d+}
        -
            controller: GameCopyListBoxController
            route: gamecopy:listbox
            url: /{convent_id:\d+}/gamecopy/{room_id:\d+}/listbox
        -
            controller: GameCopyToBoxController
            route: gamecopy:movetobox
            url: /{convent_id:\d+}/gamecopy/{room_id:\d+}/movetobox/{obj_id:\d+}

gameborrow:
    controllers:
        -
            controller: GameBorrowListController
            route: gameborrow:list
            url: /{convent_id:\d+}/game/{room_id:\d+}/borrows
        -
            controller: GameBorrowAddController
            route: gameborrow:add
            url: /{convent_id:\d+}/game/{room_id:\d+}/borrows/add/{obj_id:\d+}
        -
            controller: GameBorrowReturnController
            route: gameborrow:return
            url: /{convent_id:\d+}/game/{room_id:\d+}/borrows/return/{obj_id:\d+}

statistics:
    controllers:
        -
            controller: StatisticsController
            route: statistics:all
            url: /{convent_id:\d+}/statistics

auth:
    controllers:
        -
            controller: AuthListController
            route: auth:list
            url: /auth
        -
            controller: AuthEditController
            route: auth:edit
            url: /auth/edit/{obj_id:\d+}
        -
            controller: AuthAddController
            route: auth:add
            url: /auth/add
        -
            controller: AuthEditSelfController
            route: auth:editself
            url: /profile/edit
